# Generated by Django 5.1.6 on 2025-04-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("number", models.TextField(blank=True, default="", help_text="The number of the Caltrans district")),
                ("name", models.TextField(blank=True, default="", help_text="The short name of the Caltrans district")),
            ],
        ),
    ]
